# Generated by Django 3.0.1 on 2019-12-29 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrow',
            name='row_num',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentrow',
            name='certificate_number',
            field=models.CharField(max_length=30, verbose_name='Номер аттестационного дела'),
        ),
        migrations.AlterField(
            model_name='documentrow',
            name='defence_date',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Дата защиты'),
        ),
        migrations.AlterField(
            model_name='documentrow',
            name='registration_date',
            field=models.CharField(max_length=8, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='speciality_name',
            field=models.CharField(max_length=115, verbose_name='Наименование специальности'),
        ),
    ]
