# Generated by Django 3.0.1 on 2020-01-16 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20191229_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='science',
            name='science_code',
            field=models.CharField(default='', max_length=2, verbose_name='Код науки'),
            preserve_default=False,
        ),
    ]
