# Generated by Django 3.0.1 on 2020-01-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_science_science_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrow',
            name='decision_num',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Номер решения'),
        ),
        migrations.AlterField(
            model_name='documentrow',
            name='defence_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата защиты'),
        ),
        migrations.AlterField(
            model_name='documentrow',
            name='registration_date',
            field=models.DateTimeField(verbose_name='Дата регистрации'),
        ),
    ]
