# Generated by Django 3.0.1 on 2020-01-28 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20200126_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preamble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preamble_short', models.CharField(max_length=10, verbose_name='Преамбула кор.')),
                ('preamble', models.CharField(max_length=120, verbose_name='Преамбула')),
            ],
        ),
        migrations.RemoveField(
            model_name='university',
            name='university_preamble',
        ),
        migrations.AlterField(
            model_name='university',
            name='university_name',
            field=models.CharField(db_index=True, max_length=120, verbose_name='Наименование университета'),
        ),
        migrations.AddField(
            model_name='university',
            name='preamble',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='document.Preamble', verbose_name='Тип документа'),
            preserve_default=False,
        ),
    ]
