# Generated by Django 3.0.1 on 2020-01-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20200128_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speciality',
            name='speciality_name',
            field=models.CharField(max_length=150, verbose_name='Наименование специальности'),
        ),
    ]
