# Generated by Django 3.0.1 on 2020-01-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_auto_20200129_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(db_index=True, max_length=110, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='preamble',
            name='preamble_short',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Преамбула кор.'),
        ),
        migrations.AlterField(
            model_name='science',
            name='science_code',
            field=models.CharField(db_index=True, max_length=2, verbose_name='Код науки'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='speciality_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Наименование специальности'),
        ),
    ]
