# Generated by Django 3.0.1 on 2020-01-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0009_auto_20200130_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrow',
            name='row_num',
        ),
    ]
