# Generated by Django 3.0.1 on 2020-01-30 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_remove_documentrow_row_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrow',
            name='science',
        ),
        migrations.AddField(
            model_name='speciality',
            name='science',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='document.Science', verbose_name='Наименование науки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentrow',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_rows', to='document.Document', verbose_name='Номер документа'),
        ),
    ]
