# Generated by Django 3.0.1 on 2020-02-02 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0012_auto_20200131_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=30, verbose_name='Номер аттестационного дела')),
                ('registration_date', models.DateTimeField(verbose_name='Дата регистрации')),
            ],
        ),
        migrations.RemoveField(
            model_name='person',
            name='certificate_number',
        ),
        migrations.RemoveField(
            model_name='person',
            name='registration_date',
        ),
        migrations.RemoveField(
            model_name='science',
            name='science_code',
        ),
        migrations.RemoveField(
            model_name='speciality',
            name='science',
        ),
        migrations.AddField(
            model_name='documentrow',
            name='science',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Science', verbose_name='Наименование науки'),
        ),
        migrations.AddField(
            model_name='person',
            name='numbers',
            field=models.ManyToManyField(related_name='numbers', to='document.CertificateNumber', verbose_name='Номер аттестационного дела'),
        ),
    ]
