# Generated by Django 3.0.1 on 2020-02-02 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0013_auto_20200202_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='numbers',
        ),
        migrations.AddField(
            model_name='certificatenumber',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='document.Person', verbose_name='УИД человека'),
            preserve_default=False,
        ),
    ]
