# Generated by Django 3.0.1 on 2020-02-02 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_auto_20200202_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrow',
            name='person',
        ),
        migrations.AddField(
            model_name='documentrow',
            name='certificate_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='document.CertificateNumber', verbose_name='УИД аттестационного дела'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.DocumentType', verbose_name='УИД типа документа'),
        ),
        migrations.AlterField(
            model_name='documentrow',
            name='council',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Council', verbose_name='УИД совета'),
        ),
        migrations.AlterField(
            model_name='documentrow',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Degree', verbose_name='УИД степени'),
        ),
        migrations.AlterField(
            model_name='documentrow',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_rows', to='document.Document', verbose_name='УИД документа'),
        ),
        migrations.AlterField(
            model_name='documentrow',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Rank', verbose_name='УИД звания'),
        ),
        migrations.AlterField(
            model_name='documentrow',
            name='science',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Science', verbose_name='УИД науки'),
        ),
        migrations.AlterField(
            model_name='documentrow',
            name='speciality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.Speciality', verbose_name='УИД специальности'),
        ),
        migrations.AlterField(
            model_name='documentrow',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='document.University', verbose_name='УИД ВУЗ'),
        ),
        migrations.AlterField(
            model_name='university',
            name='preamble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Preamble', verbose_name='УИД преамбулы'),
        ),
    ]
