# Generated by Django 3.0.3 on 2020-02-14 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0015_auto_20200202_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания документа'),
            preserve_default=False,
        ),
    ]
