# Generated by Django 3.0.3 on 2020-02-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_document_document_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Наименование документа'),
        ),
        migrations.AlterField(
            model_name='documentrow',
            name='decision_num',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='Номер решения'),
        ),
        migrations.AlterField(
            model_name='preamble',
            name='preamble',
            field=models.CharField(max_length=150, verbose_name='Преамбула'),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Наименование университета'),
        ),
    ]
